### ISSUE TITLE
Support for kernerl 6.8

### ISSUE THREAD

**Issue by Raunakabhani** [geniuskidkanyi/aic8800#6]
Drivers are not getting installed with kernel 6.8 .Requesting to upgrade drivers

**Comment by telychko** [comment]
Probably this patch can help

``` diff
diff --git a/src/aic8800_fdrv/rwnx_main.c b/src/aic8800_fdrv/rwnx_main.c
index d720c40..935ecd4 100644
--- a/src/aic8800_fdrv/rwnx_main.c
+++ b/src/aic8800_fdrv/rwnx_main.c
@@ -5794,6 +5794,7 @@ int rwnx_cfg80211_start_radar_detection(struct wiphy *wiphy,
                                     #if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 15, 0))
                                         , u32 cac_time_ms
                                     #endif
+                                        ,int id
                                         )
 {
     struct rwnx_hw *rwnx_hw = wiphy_priv(wiphy);
diff --git a/src/aic8800_fdrv/rwnx_radar.c b/src/aic8800_fdrv/rwnx_radar.c
index d4ea9d2..7073b5b 100644
--- a/src/aic8800_fdrv/rwnx_radar.c
+++ b/src/aic8800_fdrv/rwnx_radar.c
@@ -1399,7 +1399,7 @@ static void rwnx_radar_cac_work(struct work_struct *ws)
                     #if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0)
                        &ctxt->chan_def,
                     #endif
-                       NL80211_RADAR_CAC_FINISHED, GFP_KERNEL);
+                       NL80211_RADAR_CAC_FINISHED, GFP_KERNEL, 0);
     rwnx_send_apm_stop_cac_req(rwnx_hw, radar->cac_vif);
     rwnx_chanctx_unlink(radar->cac_vif);

@@ -1499,7 +1499,7 @@ void rwnx_radar_cancel_cac(struct rwnx_radar *radar)
                         #if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0)
                            &ctxt->chan_def,
                         #endif
-                           NL80211_RADAR_CAC_ABORTED, GFP_KERNEL);
+                           NL80211_RADAR_CAC_ABORTED, GFP_KERNEL, 0);
         rwnx_chanctx_unlink(radar->cac_vif);
     }
```

**Comment by AlainDeroy** [comment]
Hi,

I'm running into the same problem on Kubuntu and KDE Neon. I made the changes you suggested above but still no luck.

I've attached my make.log

Would be great if You can have a look.

[make.log](https://github.com/user-attachments/files/20820064/make.log)

**Comment by geniuskidkanyi** [comment]
The current version is not compatible with 6.8, I will work on an upgrade

**Comment by geniuskidkanyi** [comment]
> Probably this patch can help
> 
> diff --git a/src/aic8800_fdrv/rwnx_main.c b/src/aic8800_fdrv/rwnx_main.c
> index d720c40..935ecd4 100644
> --- a/src/aic8800_fdrv/rwnx_main.c
> +++ b/src/aic8800_fdrv/rwnx_main.c
> @@ -5794,6 +5794,7 @@ int rwnx_cfg80211_start_radar_detection(struct wiphy *wiphy,
>                                      #if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 15, 0))
>                                          , u32 cac_time_ms
>                                      #endif
> +                                        ,int id
>                                          )
>  {
>      struct rwnx_hw *rwnx_hw = wiphy_priv(wiphy);
> diff --git a/src/aic8800_fdrv/rwnx_radar.c b/src/aic8800_fdrv/rwnx_radar.c
> index d4ea9d2..7073b5b 100644
> --- a/src/aic8800_fdrv/rwnx_radar.c
> +++ b/src/aic8800_fdrv/rwnx_radar.c
> @@ -1399,7 +1399,7 @@ static void rwnx_radar_cac_work(struct work_struct *ws)
>                      #if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0)
>                         &ctxt->chan_def,
>                      #endif
> -                       NL80211_RADAR_CAC_FINISHED, GFP_KERNEL);
> +                       NL80211_RADAR_CAC_FINISHED, GFP_KERNEL, 0);
>      rwnx_send_apm_stop_cac_req(rwnx_hw, radar->cac_vif);
>      rwnx_chanctx_unlink(radar->cac_vif);
> 
> @@ -1499,7 +1499,7 @@ void rwnx_radar_cancel_cac(struct rwnx_radar *radar)
>                          #if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0)
>                             &ctxt->chan_def,
>                          #endif
> -                           NL80211_RADAR_CAC_ABORTED, GFP_KERNEL);
> +                           NL80211_RADAR_CAC_ABORTED, GFP_KERNEL, 0);
>          rwnx_chanctx_unlink(radar->cac_vif);
>      }

Open a pr so that I can merge it

**Comment by Wolf35978** [comment]
I run into a similar error on Kernel "6.8.0-63-generic". I tried to make the mentioned changes, but it wont work. But I'm no expert at all.
Thats the error:
"arch='x86_64' kernelver='6.8.0-63-generic' ./driverctl make all....(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.8.0-63-generic (x86_64)
Consult /var/lib/dkms/aic8800/1.0.5/build/make.log for more information."

I solved it in line 1061 of rwnx_main.c: There must be an additional zero at the end of the line, like in the line below.

**Comment by m0nkeyc0de** [comment]
I'm on **Ubuntu 24.04.3 LTS** with kernel `6.8.0-86-generic` and I'm totally unable to install this driver. It just doesn't work on the most popular Linux distribution, on a LTS release. @geniuskidkanyi do you have an ETA for kernel 6.8 support ? That would be great.

I tried all the tricks provided above do not work and I'm ending up with this error:
```
/var/lib/dkms/aic8800/1.0.5/build/aic8800_fdrv/rwnx_main.c:6954:30: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_chan_def *, u32)’ {aka ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_chan_def *, unsigned int)’} from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_chan_def *, u32,  int)’ {aka ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_chan_def *, unsigned int,  int)’} [-Werror=incompatible-pointer-types]
 6954 |     .start_radar_detection = rwnx_cfg80211_start_radar_detection,
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/aic8800/1.0.5/build/aic8800_fdrv/rwnx_main.c:6954:30: note: (near initialization for ‘rwnx_cfg80211_ops.start_radar_detection’)
```
As I'm not fluent in C at all, I'm stuck here.

Below is what I've patched so far:
```diff
diff --git a/src/aic8800_fdrv/rwnx_main.c b/src/aic8800_fdrv/rwnx_main.c
index d720c40..0060f13 100644
--- a/src/aic8800_fdrv/rwnx_main.c
+++ b/src/aic8800_fdrv/rwnx_main.c
@@ -1057,8 +1057,8 @@ static void rwnx_csa_finish(struct work_struct *ws)
             rwnx_txq_vif_stop(vif, RWNX_TXQ_STOP_CHAN, rwnx_hw);
         spin_unlock_bh(&rwnx_hw->cb_lock);
 
-#if (LINUX_VERSION_CODE >- KERNEL_VERSION(6, 9, 0))
-                cfg80211_ch_switch_notify(vif->ndev, &csa->chandef, 0);
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(6, 8, 0))
+                cfg80211_ch_switch_notify(vif->ndev, &csa->chandef, 0, 0);
 #elif (LINUX_VERSION_CODE >= KERNEL_VERSION(6, 3, 0))
                 cfg80211_ch_switch_notify(vif->ndev, &csa->chandef, 0, 0);
 #elif (LINUX_VERSION_CODE >=KERNEL_VERSION(5, 19, 2))
@@ -5794,6 +5794,7 @@ int rwnx_cfg80211_start_radar_detection(struct wiphy *wiphy,
                                     #if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 15, 0))
                                         , u32 cac_time_ms
                                     #endif
+                                       , int id
                                         )
 {
     struct rwnx_hw *rwnx_hw = wiphy_priv(wiphy);
diff --git a/src/aic8800_fdrv/rwnx_radar.c b/src/aic8800_fdrv/rwnx_radar.c
index d4ea9d2..7073b5b 100644
--- a/src/aic8800_fdrv/rwnx_radar.c
+++ b/src/aic8800_fdrv/rwnx_radar.c
@@ -1399,7 +1399,7 @@ static void rwnx_radar_cac_work(struct work_struct *ws)
                     #if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0)
                        &ctxt->chan_def,
                     #endif
-                       NL80211_RADAR_CAC_FINISHED, GFP_KERNEL);
+                       NL80211_RADAR_CAC_FINISHED, GFP_KERNEL, 0);
     rwnx_send_apm_stop_cac_req(rwnx_hw, radar->cac_vif);
     rwnx_chanctx_unlink(radar->cac_vif);
 
@@ -1499,7 +1499,7 @@ void rwnx_radar_cancel_cac(struct rwnx_radar *radar)
                         #if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 14, 0)
                            &ctxt->chan_def,
                         #endif
-                           NL80211_RADAR_CAC_ABORTED, GFP_KERNEL);
+                           NL80211_RADAR_CAC_ABORTED, GFP_KERNEL, 0);
         rwnx_chanctx_unlink(radar->cac_vif);
     }
```

**Comment by morjaradat** [comment]
check my fix ===>  repo "https://github.com/morjaradat/ugreen-cm762-linux-driver"
