### ISSUE TITLE
Kernel 6.17 compatibility fixes for AIC8800D80 (working, may need refinement)

### ISSUE THREAD

**Issue by 0chustaff** [geniuskidkanyi/aic8800#10]
## AIC8800D80 working on Linux kernel 6.17 (fixes + notes from testing)

Hi,

I tested this driver with an AIC8800D80 USB Wi-Fi adapter on Linux kernel 6.17 and encountered multiple compilation errors due to API changes in newer kernel versions.

After several attempts (and with some assistance), I managed to fix the issues and get the device working. I'm sharing my results in case they are useful.

---

### ⚠️ Important note

I am not an experienced kernel or driver developer.  
Some parts of my solution may be incomplete, suboptimal, or based on trial-and-error rather than deep technical knowledge.

If anything here is incorrect or could be improved, that is likely due to my limited experience.

---

### Environment

- Kernel: 6.17.0
- Distro: Linux Mint
- Chipset: AIC8800D80
- USB ID (after modeswitch): 368b:8d81

---

### Summary of fixes applied

- Updated `cfg80211` API usage:
  - Added new parameters such as `link_id` and `radio_idx`
- Replaced deprecated timer functions:
  - `del_timer_sync` → `timer_delete_sync`
  - `del_timer` → `timer_delete`
  - `from_timer` → `timer_container_of`
- Fixed `MODULE_IMPORT_NS` syntax (string literal now required)
- Updated several function signatures to match kernel 6.17
- Added support for USB device `368b:8d81` in the driver

---

### Runtime behavior and notes

- The device initially appears as:

a69c:5721 (mass storage mode)

- After `usb_modeswitch`, it becomes:

368b:8d81 (Wi-Fi mode)

- In my case, I still needed to manually bind the device:

  ```bash
  echo "368b 8d81" > /sys/bus/usb/drivers/aic8800_fdrv/new_id

This might indicate that:

the device is not fully matched by the current usb_id_table, or
there is some interface matching issue

I'm not fully sure about the root cause.

Notes on D80 vs D81

Although the chipset is AIC8800D80, the USB ID reported after modeswitch is 8d81, which corresponds to the D81 entry in the driver.

I am not certain if this is expected behavior or a quirk of this hardware.

Result
Wi-Fi interface appears correctly
Able to connect to networks
Works in normal usage (basic testing)
Full documentation

I documented the full process here:

👉 https://github.com/0chustaff/aic8800-linux-kernel-6.17

I'm just sharing this in case it helps others running into the same issue.

If this is useful and you want a proper patch version, I can try to organize my changes — but I might need guidance due to my limited experience.

Thanks for your work on this driver.
